name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '33 * * * *'

uses: sergeysova/jq-action@v2
with:
  cmd: jq -n env

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl https://api.github.com/repos/PrefectHQ/prefect | jq . > paparazzo.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
